sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nitinskav/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nitinskav/react-test npm test

after_success:
  - docker build -t nitinskav/multi-client ./client
  - docker build -t nitinskav/multi-nginx ./nginx
  - docker build -t nitinskav/multi-server ./server
  - docker build -t nitinskav/multi-worker ./worker

  # login to dockercli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  # images pushed to dockerhub
  - docker push nitinskav/multi-client
  - docker push nitinskav/multi-nginx
  - docker push nitinskav/multi-server
  - docker push nitinskav/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-706051624453"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  